language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: rodrigoamaral
  password:
    secure: MNAPJ0Xc1EXzXIf8kQFbuwdhEcdauY6iScqvcx/46S17ximCD9653hpSuiNznXWgKK+eqYgzqLItmH0+PZKTEw5xQVHvg2v4kEM1z31rXeJK+L7DXSCo3m48AAIx9WoeE7P0vpDJB1b59/aPF/GwGtPNIi8IO/gvjCfc/FSoURk2b+rQwNGmEkenVVKaCqol3UUVBHicn7rQhSWnkq7ifWcU6RDjQmlfOctLDKgEDo2scBEQc0gzuEtGPJqOKt5+F84g9NLOqU3AZ89TW4iTXGd8gojfBOq4N6nUL2HX+wktAWiAyHynLrbheKTl8FB6HvOGbp01ML8M/5qDz1Qd8JqRpOMsf1cxh1ldNU0pc0azrKcUz+IlUPkrQunENAoE1KKZZHIqQzjje6VpeYnLVz+0KooUrCAXE/b8juuxrxsmZdwYu56M+7zgIsmCZTyIEdKMrw7ZmnH9lyqjdu4Vf+z+O9NiOkWzgS3X/IGUApFuVPDU47GXTb9V1PVOSLfBhamxtnZETkhltgPz25OhiHFZiaAFpIeRpOG1bXl/Fyalh46+f05pqG/u28hfHEdDi0VQF4fgrwyx9XJWyTlWYQvDTDuJm64dkKSmRmqdSWWsY9xVKflaEY3Zz1dktlMUHLb2Xoe6flY+H3rbu/B2ZblL0Iaer5iufBcc1K24dcE=
  on:
    tags: true
    repo: rodrigoamaral/dynapsp
    python: 3.6
